### ISSUE TITLE
cicd.md

### ISSUE THREAD

**Issue by Earth34r** [CSE-210-Team-11/cse210-fa24-group-11#18]
For the satisfactory completion of this process, you should provide the following items and store them in your repo under /admin/cipipeline by Nov 17th, 2024 (End of week 7)

cicd.png: a diagram of your build pipeline (can be cicd.drawio.png if using draw.io).
cicd.md: a short 2-page (roughly) status on the pipeline in terms of what is currently functional (and what is planned or in progress). Embed your diagram in the markdown file.

**Comment by Xcode-wu** [comment]
Maekdown file uploades
