### ISSUE TITLE
ADR for Code Quality Tool

### ISSUE THREAD

**Issue by SirKanaad26** [CSE-210-Team-11/cse210-fa24-group-11#3]
We are exploring several different code quality tools - and thus, we require an ADR to address the need for it.

**Comment by DylanLukes** [comment]
This seems like a reasonable choice to me given the project timeframe and scope. Biome is very opinionated, which removes a lot of configuration overhead and allows you to settle the issue and move on. 

A downside can be that you may not always love how it does everything, but having something consistent in place probably outweighs that. 

In any case, code style tools are one of the easier components to change at a later date if desired, and it's generally very in line with the same defaults as other more enduring tools like Prettier.
