### ISSUE TITLE
Enhanced User Authentication and Skills Management

### ISSUE THREAD

**Issue by jain-atishay** [CSE-210-Team-11/cse210-fa24-group-11#30]
Major dashboard improvements:
- Implemented secure login/logout flow
- Added personalized welcome message display
- Enhanced session management
- Added skills search functionality with case-insensitive matching
- Implemented category-based filtering
- Added search button for better UX
- Improved skills organization by categories
- Enhanced visual feedback for search results

**Comment by Earth34r** [comment]
Removed from design
