### ISSUE TITLE
Tree artwork on page bottom

### ISSUE THREAD

**Issue by Earth34r** [CSE-210-Team-11/cse210-fa24-group-11#42]

**Comment by jain-atishay** [comment]
Refer this [gist code](https://gist.github.com/jain-atishay/7dc4dd2a8063fcc3d3394f044fea97aa) for the Tree art for homepage bottom.

**Comment by jain-atishay** [comment]
This is recommended styling in [gist](https://gist.github.com/jain-atishay/8c4efd456e9198b1d44c242ab13b93da)
