### ISSUE TITLE
Tree growth percentage -> Render tree on canvas

### ISSUE THREAD

**Issue by Earth34r** [CSE-210-Team-11/cse210-fa24-group-11#55]

**Comment by lezhangleonard** [comment]
![Screenshot 2024-11-27 at 4 25 38 PM](https://github.com/user-attachments/assets/5aed49fe-b428-4e21-8a49-45355dbb9632)

**Comment by lezhangleonard** [comment]
![image](https://github.com/user-attachments/assets/78602ecd-00bd-4719-adba-61da79f708e6)
