### ISSUE TITLE
Creating Project-List JSON Objects

### ISSUE THREAD

**Issue by SirKanaad26** [CSE-210-Team-11/cse210-fa24-group-11#71]

**Comment by jain-atishay** [comment]
This [gist](https://gist.github.com/jain-atishay/209baedaf69499d1cfb41e5aedb25615) file is for C++ project path Json file

**Comment by jain-atishay** [comment]
I believe this [gist](https://gist.github.com/jain-atishay/26e89145c998a53e3af7f23b1f24ed70) should be more appropriate as it includes sub tasks too in the structure

**Comment by jain-atishay** [comment]
This is the [gist](https://gist.github.com/jain-atishay/a55bd1a177bc3a1ae6e054779f0efe0f) file for Python template for Project page

**Comment by jain-atishay** [comment]
This [gist](https://gist.github.com/jain-atishay/738becca5b6563d5186a6d8cc8c8781d) file contains the json data for Java template for project page

**Comment by jain-atishay** [comment]
This [gist](https://gist.github.com/jain-atishay/d4f6660f4d148b7f44c63913858c9b55) has json data for project template Beginner front end learner

**Comment by jain-atishay** [comment]
This is [gist](https://gist.github.com/jain-atishay/b2722a8c175df48fa80efaa409e1615e) has the needed Json data for modules and subtasks for template of Gen AI beginner

**Comment by Earth34r** [comment]
Completed in #82
